version: 2.1

defaults: &defaults
  docker: 
    - image: jcuffney/node-ci-image:1.0.25
  working_directory: ~/repo

jobs:

  deps: 
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test

  build: 
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - save_cache:
          paths:
            - build
          key: v1-build-{{ checksum "package.json" }}


  publish:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  validate:
    jobs:
      - deps
      - test:
          requires:
            - deps
      - build:
          requires:
            - deps
      - publish:
          context: NPM
          requires:
            - deps
            - test
            - build
          filters:
            branches:
              only: master
